name: 質問フォーム
description: 教材やオリジナルアプリの作成で質問したいことがある際に使用してください
title: "[質問]: "
labels: ["question"]
assignees:
  - junkchi89
  - nakajima432
body:
  - type: markdown
    attributes:
      value: |
        質問ありがとうございます！下記のフォームの内容を記述してください。
  - type: dropdown
    id: taking_course
    attributes:
      label: 受講しているコース
      description: 現在受講しているコースを選択してください
      options:
        - web制作
        - Webアプリ
        - データサイエンス
    validations:
      required: true
  - type: input
    id: curriculum
    attributes:
      label: 教材名
      description: 学習している教材名、または、オリジナルポートフォリオ作成など
      placeholder: ex. Visual Studio Code入門、　オリジナルポートフォリオ
    validations:
      required: true
  - type: input
    id: purpose_to_question
    attributes:
      label: 前提・実現したいこと
      description: 一言で実装したいことを書いてください
      placeholder: ex.　画面真っ白になるバグを解消したい
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 問題点/エラー内容/エラー文章
      description: 現在起きているエラーや状況をお伝えください
      placeholder: リンクボタンをクリックしたら、画面が白くなりました。
      value: 
    validations:
      required: false
  - type: dropdown
    id: language
    attributes:
      label: 学習している教材に関連する言語
      multiple: true
      options:
        - HTML
        - CSS
        - SASS/SCSS
        - Web制作
        - Wordpress
        - JSDOM
        - JavaScript
        - TypeScript
        - React
        - Vue
        - Next
        - Nuxt
        - Firebase
        - Supabase
        - Prisma
        - Node.js
        - Docker
  - type: textarea
    id: assuming_process
    attributes:
      label: 想定している処理の流れ
      description: 想定している処理の流れを箇条書きで記述してください
      value: 
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    id: code_or_url
    attributes:
      label: 該当ソースコード/コマンド、または、コードURL(Github、Fiddle、Codepenなど該当コードファイル)
      description:
      value: 
    validations:
      required: false
  - type: textarea
    id: what_you_search
    attributes:
      label: 試したことや調べたこと
      description: 自分で調べたことや試したことを記述してください（1サイト以上確認、推奨）
      value: 
    validations:
      required: false
  - type: textarea
    id: something
    attributes:
      label: その他
      description: その他、何か伝えたいことがあれば記載してください
      value: 
    validations:
      required: false
